version: "1"
name: List Splunk Indices
enabled: true
triggers:
  - type: manual
    enabled: true
consts:
  splunk_url: https://splunkurl.com:8089
  splunk_auth: Basic xxxxxxxxx
steps:
  - name: list_splunk_indices
    type: http
    with:
      url: "{{consts.splunk_url}}/services/search/jobs"
      method: POST
      headers:
        Content-Type: application/x-www-form-urlencoded
        Authorization: "{{consts.splunk_auth}}"
      body: "search=%7Crest%20%2Fservices%2Fdata%2Findexes%20count%3D0%20datatype%3Dall%20%7C%20search%20totalEventCount%20%3E%200%20title%20!%3D%20_*%20%7C%20table%20title%20totalEventCount&count=0&output_mode=json"
      timeout: 30s
  - name: wait_for_search
    type: wait
    with:
      duration: 5s
  - name: get_splunk_results
    type: http
    with:
      url: "{{consts.splunk_url}}/services/search/jobs/{{steps.list_splunk_indices.output.data.sid}}/results?output_mode=json&count=0"
      method: GET
      headers:
        Authorization: "{{consts.splunk_auth}}"
      timeout: 30s 

      
